feat: adds edge bridge and xdm mapping events
adobe/griffon-toolkit pull request #48
Opened 2022-11-16 04:50 UTC by dsoffiantini

## Description

Adds in events used in upcoming analytics changes

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-16 17:19 UTC, dgrossen commented on packages/aep-mobile/schemas/xdmMapping.json
> +              "inherit": true,
not sure what this is inheriting. Noticed the `analyticsMapping` schema has this as well...

2022-11-16 17:19 UTC, dgrossen requested changes
should the xdmMapping event go in the edge package? Otherwise looks good

2022-11-18 18:38 UTC, amadt commented on packages/edge/schemas/edgeBridgeRequest.json
> +    { "$ref": "http://griffon.adobe.com/schemas/aep-mobile/mobileEvent" }
Since this one does extend mobile, it should actually go in the mobile package 😄 

Basically, edge events would be common for both web and mobile, where thins with `ACPExtensionEventData` are following a mobile specific format.

2022-11-22 19:11 UTC, dgrossen approved these changes

2022-11-22 20:09 UTC, amadt approved these changes

2022-11-23 17:27 UTC, merged